---
# handlers file for setup-apache

- name: Start service httpd, if not started
  service:
    name: httpd
    state: started

- name: restart httpd
  service:
    name: httpd
    state: restarted

